# Generated by Django 3.2.6 on 2024-05-25 09:19

import app.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Name')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='City')),
                ('council', models.CharField(blank=True, max_length=30, verbose_name='Council')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='Country')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='RelativesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order_by', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Relatives Relation',
                'verbose_name_plural': 'Relatives Relations',
                'db_table': 'relatives_relation',
                'ordering': ['order_by'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=30, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=70, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nic', models.CharField(default='99999-9999999-9', help_text='National ID number', max_length=20, unique=True, verbose_name='CNIC')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not to be disclosed')], max_length=1)),
                ('marital_status', models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed')], default=1)),
                ('cellphone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp_cellphone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_address', models.CharField(blank=True, max_length=150)),
                ('permanent_address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='Belonging City')),
                ('person_id', models.CharField(max_length=20, unique=True, verbose_name='Person ID')),
                ('avatar', models.ImageField(blank=True, max_length=200, null=True, upload_to=app.core.models.avatar_uploading_path, verbose_name='Profile Picture')),
                ('thumbnail', models.ImageField(blank=True, max_length=200, null=True, upload_to=app.core.models.avatar_uploading_path, verbose_name='Profile Thumbnail')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_loggable', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='core.area')),
                ('emergency_contact_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='core.relativesrelation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'person',
                'ordering': ['full_name'],
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='core.region'),
        ),
    ]
