# Generated by Django 3.2.6 on 2024-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not to be disclosed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='nic',
            field=models.CharField(help_text='National ID number', max_length=20, null=True, unique=True, verbose_name='CNIC'),
        ),
    ]
