# Generated by Django 3.2.6 on 2024-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20240619_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='community_cover_images/'),
        ),
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='community_logos/'),
        ),
    ]
